version: "3.0"

services:
  dataentry-sql-server:
    build: './gs1resolver_dataentry_db'
    container_name: dataentry-sql-server
    volumes:
      - gs1resolver-dataentry-volume:/gs1resolver_data
      - gs1resolver-dbbackup-volume:/dbbackup
    restart: always
    networks:
      - gs1-resolver-network
    ports:
      - "3333:1433"

  id-mongo-server:
    build: './gs1resolver_document_db'
    container_name: id-mongo-server
    restart: always
    volumes:
      - gs1resolver-document-volume:/data/db
    networks:
      - gs1-resolver-network
    ports:
      - "27017:27017"

  gs1dl-toolkit-server:
    build: './dl_toolkit_server'
    container_name: gs1dl-toolkit-server
    restart: always
    networks:
      - gs1-resolver-network

  dataentry-web-server:
    build: './dataentry_web_server'
    container_name: dataentry-web-server
    depends_on:
      - dataentry-sql-server
      - id-mongo-server
      - gs1dl-toolkit-server
    restart: always
    networks:
      - gs1-resolver-network

  id-web-server:
    build: './id_web_server'
    container_name: id-web-server
    depends_on:
      - id-mongo-server
    restart: always
    ports:
      - "8080:80"
    networks:
      - gs1-resolver-network

  unixtime-web-server:
    build: './unixtime_web_server'
    container_name: unixtime-web-server
    restart: always
    networks:
      - gs1-resolver-network

volumes:
  gs1resolver-dataentry-volume: {}
  gs1resolver-document-volume: {}
  gs1resolver-dbbackup-volume: {}

networks:
  gs1-resolver-network: {}