version: "3.0"

services:
  dataentry-sql-server:
    build: './gs1resolver_dataentry_db'
    container_name: dataentry-sql-server
    volumes:
      - gs1resolver-dataentry-volume-db-data:/var/opt/mssql/data
      - gs1resolver-dataentry-volume-db-log:/var/opt/mssql/log
      - gs1resolver-dataentry-volume-db-secrets:/var/opt/mssql/secrets
      - gs1resolver-dbbackup-volume:/dbbackup
    restart: always
    networks:
      - gs1-resolver-network

  id-mongo-server:
    build: './gs1resolver_document_db'
    container_name: id-mongo-server
    restart: always
    ports:
      - "27012:27012"
    volumes:
      - gs1resolver-document-volume:/data/db
    networks:
      - gs1-resolver-network

  dataentry-web-server:
    build: './dataentry_web_server'
    container_name: dataentry-web-server
    depends_on:
      - dataentry-sql-server
      - id-mongo-server
    restart: always
    networks:
      - gs1-resolver-network

  id-web-server:
    build: './id_web_server'
    container_name: id-web-server
    depends_on:
      - id-mongo-server
    restart: always
    networks:
      - gs1-resolver-network

  frontend-proxy-server:
    build: './frontend_proxy_server'
    container_name: frontend-proxy-server
    depends_on:
      - id-web-server
      - dataentry-web-server
    restart: always
    ports:
      - "8080:80"
    networks:
      - gs1-resolver-network

volumes:
  gs1resolver-dataentry-volume-db-data: {}
  gs1resolver-dataentry-volume-db-log: {}
  gs1resolver-dataentry-volume-db-secrets: {}
  gs1resolver-document-volume: {}
  gs1resolver-dbbackup-volume: {}

networks:
  gs1-resolver-network: {}