version: "3.6"

services:
  resolver-mongo-service:
    build: './resolver_mongo_server'
    container_name: resolver-mongo-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - resolver-document-volume:/data/db
    networks:
      - resolver-internal-network

  resolver-sql-server:
    build: './resolver_sql_server'
    container_name: resolver-sql-server
    ports:
      - "1433:1433"
    volumes:
      - resolver-sql-server-volume-db-data:/var/opt/mssql/data
      - resolver-sql-server-volume-db-log:/var/opt/mssql/log
      - resolver-sql-server-volume-db-secrets:/var/opt/mssql/secrets
      - resolver-sql-server-dbbackup-volume:/dbbackup
    restart: always
    networks:
      - resolver-internal-network

  digitallink-toolkit-service:
    build: "./digitallink_toolkit_server"
    container_name: digitallink-toolkit-server
    restart: always
    networks:
      - resolver-internal-network

  build-sync-service:
    build: './build_sync_server'
    container_name: build-sync-server
    depends_on:
      - resolver-mongo-service
    restart: always
    networks:
      - resolver-internal-network

  data-entry-service:
    build: './resolver_data_entry_server'
    container_name: resolver-data-entry-server
    depends_on:
      - resolver-mongo-service
    restart: always
    networks:
      - resolver-internal-network

  id-service:
    build: './resolver_web_server'
    container_name: resolver-web-server
    depends_on:
      - resolver-mongo-service
    restart: always
    networks:
      - resolver-internal-network

  frontend-proxy-service:
    build: './frontend_proxy_server'
    container_name: frontend-proxy-server
    depends_on:
      - id-service
    restart: always
    ports:
      - "80:80"
    networks:
      - resolver-internal-network

networks:
  resolver-internal-network:
    name: resolver-internal-network

volumes:
  resolver-document-volume: {}
  resolver-sql-server-volume-db-data: {}
  resolver-sql-server-volume-db-log: {}
  resolver-sql-server-volume-db-secrets: {}
  resolver-sql-server-dbbackup-volume: {}